### ISSUE TITLE
Practice Drivetrain Calibration

### ISSUE THREAD

**Issue by nstojcevich** [frc-862/glitch#22]

**Comment by phurley** [comment]
This is in process, but cannot really be done without glitch. Move to feature complete? Do we need another milestone glitch +1 (things that need to be done as soon as we get glitch)?

**Comment by phurley** [comment]
On Saturday we are going to practice with obot, when that work is complete we will close this issue.

1. Using open loop, run low and high gear samples from stop to full speed several times and log
2. Examine and graph logs, determine max speed and max calibrated speed (in ticks/100ms)
3. Based on max calibrated speed, set optimal feed forwards and zero out other PID constants
4. Make the same runs, also graphing left/right error
5. Crank up the P constant and do it again
6. Adjust PID as necessary to get desired response
