### ISSUE TITLE
Write Auton Pseudo Code (stories)

### ISSUE THREAD

**Issue by nstojcevich** [frc-862/glitch#33]

**Comment by phurley** [comment]
Please do the following, consider our current driver station input choices:

Red/Blue Alliance (we get this from driver station, not the drive team)
Left Side/Right Side (need to get this from the dashboard)
Count on your partner (yes/no from the dashboard)
Switch/Scale priority (from the dashboard)

At this point we are only considering single power cube auton (once these work we can try for two). Using the cheesy_path web app, route a path. Be sure and set a consistent start position. Also Provide a short bit of text describing how the field configuration affects which option is select.

**Comment by phurley** [comment]
https://github.com/frc-862/glitch/wiki/Auton-Stories
