### ISSUE TITLE
Autoshifting

### ISSUE THREAD

**Issue by nstojcevich** [frc-862/glitch#4]

**Comment by phurley** [comment]
See code from Valkyrie, should be a relatively easy port, implement as the default command on the shifter subsystem.

https://github.com/frc-862/valkyrie/blob/master/src/org/usfirst/frc862/valkyrie/commands/Autoshifter.java

**Comment by phurley** [comment]
After completing #22 practice (we will need a very similar issue for glitch), use generated graphs to determine optimal shift point and implement upshift/downshifts using valkyrie code.
